### ISSUE TITLE
Facebook Login 

### ISSUE THREAD

**Issue by sukk630** [hippogamesunity/SimpleSignIn#10]
Login using facebook failed: show Tips is   "Application not enabled
The app is currently unavailable and the app developer has been made aware of the issue. Once the app is enabled again, you'll be able to log in."

**Comment by hippogamesunity** [comment]
Hello, how can I help you? Make sure your app is properly configured and enabled in your developer console.

**Comment by sukk630** [comment]
When I used demo to log in to Facebook, the page popped up after I clicked on login, and then input my Facebook account. After clicking on login, the page would pop up a prompt "Application not enabled.
The app is currently unavailable and the app developer has been made aware of the issue. Once the app is enabled again, you'll be able to log in.“

**Comment by hippogamesunity** [comment]
Did you try setting your app? Don't use default settings.

вт, 16 июл. 2024 г., 13:29 sukk630 ***@***.***>:

**Comment by sukk630** [comment]
I also tried, I want to ask, when creating the app type can choose Game, I saw on the Wiki selection (type: Other/Consumer), is it necessary to create the type of Other/Consumer APP can log in normally

**Comment by hippogamesunity** [comment]
Right, it should be Other.

вт, 16 июл. 2024 г., 13:47 sukk630 ***@***.***>:

**Comment by sukk630** [comment]
Must it be (type: Other/Consumer) , can't it be game type?

**Comment by hippogamesunity** [comment]
You can try Game, I don't have any info on this, sorry.

ср, 17 июл. 2024 г., 04:50 sukk630 ***@***.***>:

**Comment by sukk630** [comment]
Now the facebook developer background has changed, the application type created does not have the option (type: Other/Consumer), I do not know whether the current login scheme can still adapt to the new facebook policy requirements

**Comment by hippogamesunity** [comment]
I'll check this.

ср, 17 июл. 2024 г., 09:51 sukk630 ***@***.***>:

**Comment by hippogamesunity** [comment]
Did you try this option?
![image](https://github.com/user-attachments/assets/279d1fa5-eebf-445b-93f4-45cc778ef852)
Facebook Login is what we need.

**Comment by hippogamesunity** [comment]
I've updated WIKI. They've just changed admin UI.
https://github.com/hippogamesunity/SimpleSignIn/wiki/Facebook

**Comment by sukk630** [comment]
Yes, I do. (type: Authenticate and request data from users with Facebook Login)
Does your demo work? When I run it, the page shows an error
![Dingtalk_Facebook1](https://github.com/user-attachments/assets/112ba0ff-5a8b-4363-ab84-62b9e0a77275)

**Comment by hippogamesunity** [comment]
The test app was switched to App Mode: Development. Now I've switched it to Live. Note that you shouldn't use default app settings. Also note that Localhost Loopback is only allowed for apps in App Mode: Development.
I've updated the asset to v2.5: Editor flow has been switched from LoopbackFlow to AuthorizationMiddleware.

**Comment by hippogamesunity** [comment]
Please let me know if your issue is now solved.
