### ISSUE TITLE
Twitter login problem 

### ISSUE THREAD

**Issue by sukk630** [hippogamesunity/SimpleSignIn#11]
In the Demo, the Token can be obtained by calling the PerformCodeExchange function, but the RequestUserInfo function fails to return, the error code is:
 HTTP/1.1 403 Forbidden: {
"title": "Forbidden",
"type": "about:blank",
"status": 403,
"detail": "You are not permitted to use OAuth2 on this endpoint"
}.

**Comment by hippogamesunity** [comment]
Hello, what are your reproduction steps?
It works fine in my case:
![image](https://github.com/user-attachments/assets/069481a6-1a66-4ae2-b986-a5605a7d5e20)

**Comment by sukk630** [comment]
hello, three questions
1：You released Twitter version 1.2 earlier, but the image above suggests that you are running version 1.1, and in the new 1.2 release, you are wrong in a few things
![Dingtalk_20240718101147](https://github.com/user-attachments/assets/9d5dae07-5bc7-4b9b-b2f5-669817c21e3a)
In version 1.2 you added a function to handle CORS workaround. In a non-WECGL platform, UnityWebRequest does not access the URL passed in. I think this is wrong, I changed this to post URL
2：When requesting user information, a POST is created, but the correct approach is to create a GET to access it
![Dingtalk_3](https://github.com/user-attachments/assets/5acdaae1-6040-4f02-93de-ccd1222a5393)
I have recently modified the Get access and successfully obtained the user ID, name,userName。
Both of these issues are in version 1.2, so you can check them out
3：The player information returned contains only 3 fields: id,name,username. But I want to get the player Token, and Token Secret, I have checked a lot of articles have not found the way to get, you can teach me how to get in detail? It is better to attach the code. Finally, my English is not good, sorry

**Comment by sukk630** [comment]
I am in a hurry. I hope you can help me. Thank you

**Comment by hippogamesunity** [comment]
Sure, I need more time to check your info. I was using the latest version, Editor/Android. Again, how can I reproduce your issue? What are environment settings, exact steps?

**Comment by sukk630** [comment]
Just change the version you're running to version 1.2 of the store, and the error will appear.

**Comment by sukk630** [comment]
I searched the documentation of Twitter in detail, because this scheme uses Auth2.0, but twitter seems to no longer return Token and Token Secret in the request of Auth2.0. Finally, I implemented the Auth1.0 process by myself. Successfully got the player's Token Secret

**Comment by hippogamesunity** [comment]
Don't forget to check this old API support lifetime.

**Comment by hippogamesunity** [comment]
Thanks for your info! Please update to the version 1.3 and let me know if you have any issues.
