### ISSUE TITLE
The name 'Registry' does not exist in the current context

### ISSUE THREAD

**Issue by Hazzel1337** [hippogamesunity/SimpleSignIn#13]
I installed .NET framework 4.8.1 to fix the issue, didnt work

Assets\SimpleSignIn\Google\Scripts\WindowsDeepLinking.cs(43,29): error CS0103: The name 'Registry' does not exist in the current context

Assets\SimpleSignIn\Google\Scripts\WindowsDeepLinking.cs(61,29): error CS0103: The name 'Registry' does not exist in the current context

**Comment by hippogamesunity** [comment]
Hello, please check wiki and set .NET Framework

сб, 27 июл. 2024 г., 22:14 Hazzel1337 ***@***.***>:
