### ISSUE TITLE
Telegram Login Issue on iOS

### ISSUE THREAD

**Issue by shubham-or** [hippogamesunity/SimpleSignIn#14]
Hi I have been using your plugin and it works perfectly on Android. However, it is not working on iOS device running iOS 18.

This is the message printed on the console:
**BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).**

This happens when I call TelegramAuth.SignIn(OnSignIn);

Please let me know what needs to be done here.
Thanks in advanced.

**Comment by hippogamesunity** [comment]
Thanks for reporting! Does the error relates to SafariViewController.mm?

**Comment by shubham-or** [comment]
Thanks for the quick reply. This comes both when I Enable or Disable the Use Safari View Controller in the TelegramAuthSettings.

NOTE: It works perfectly on iOS 17.

**Comment by shubham-or** [comment]
@hippogamesunity Hi, did you find any solution? Please do let us know if there is any workaround, we are really stuck here.
Thanks

**Comment by hippogamesunity** [comment]
Hello! I will test it in a few days. As you said this happens even without using SafariViewController.mm, I can suggest this is simething unrelated to my asset. What version of Unity do you use? Try updating to the latest version.

Also you can easily find the same issue in Google: https://discussions.unity.com/t/can-t-use-application-openurl-on-ios-18-solved/1524320/6

**Comment by shubham-or** [comment]
Thanks, it worked after updating to 2022.3.37f.

**Comment by hippogamesunity** [comment]
Great! I will be grateful for your review, good luck!
