### ISSUE TITLE
Retrieving ServerAuthCode?

### ISSUE THREAD

**Issue by kashiftasneempro** [hippogamesunity/SimpleSignIn#16]
Hi. I am implementing [Google SignIn](https://learn.microsoft.com/en-us/rest/api/playfab/client/authentication/login-with-google-account?view=playfab-rest) using Playfab in my Unity Game. The PlayfabClient API expects a "ServerAuthCode" . I have passed both "AccessToken" and "IdentityToken" received from SimpleSignIn asset but they are being rejected. How can I get the "ServerAuthCode"?

**Comment by hippogamesunity** [comment]
Hello! This feature is not advertised. It's for internal use and I'm not sure if you can pass it to 3rd party plugins. Anyway, if you need it, you should modify asset code, the auth code is passed to PerformCodeExchange (here you can intercept it and expose with event or callback).
