### ISSUE TITLE
Apple Signin for Webgl

### ISSUE THREAD

**Issue by aayoub1** [hippogamesunity/SimpleSignIn#18]
I’m encountering a CORS issue when executing the 'https://appleid.apple.com/auth/token' API during the AppleAuth.GetAccessToken process in WEBGL build.  

Please refer to the attached image for details.  

Thank you,
Ahmad
<img width="876" alt="apple CORS failure" src="https://github.com/user-attachments/assets/faf3aef9-45fd-4aeb-a769-db55ac24b663">

**Comment by hippogamesunity** [comment]
Hello, thanks for reporting! I'll think how to help you.
By the way, you can try my another asset Play ID, it should work for WebGL as all API calls are made on the server side with this asset.

**Comment by hippogamesunity** [comment]
The only solution in this case is to use Auth Middleware as CORS proxy, delegating it to make API calls. I'm not sure, but maybe Apple has removed CORS headers. Anyway, I need more time to investigate the issue.

**Comment by hippogamesunity** [comment]
Hello, I've added CORS proxy for WebGL builds in v1.3 and tested in WebGL. Please wait a bit while it will be reviewed and published.
Also I'll be very happy to get your review on the Asset Store! Please let me know if the issue is now solved.
