### ISSUE TITLE
Microsoft sign out doesn't work in WEBGL

### ISSUE THREAD

**Issue by aayoub1** [hippogamesunity/SimpleSignIn#19]
After executing the Microsoft Auth flow on the WebGL platform, the credentials remain cached in the system even after signing out (with and without revokeAccessToken). As a result, subsequent authentication attempts do not prompt the user for credentials and instead return the cached user.

Thanks,
Ahmad

**Comment by hippogamesunity** [comment]
Hello, the SignIn call has 'caching' parameter, just use it.

**Comment by aayoub1** [comment]
Thank you for your reply.
 
This is my current flow:
microsoftAuth_.GetAccessToken((success, error, tokenResponse) =>
{
      if (!success) { return; }
      - Send the access token to my server - So the userInfo is retrieved in the server side.
      - Wait for Server handling completion -> SignOut(true)
});
--> **All** subsequent authentication attempts do not prompt the user for credentials....

Even if I change the flow to make full Signin with caching=false (as you suggest)

microsoftAuth_.SignIn((success, error, userInfo) =>{...}, false);

This doesn't help either...

Thanks,
Ahmad

**Comment by hippogamesunity** [comment]
Did you call SignOut? It should destroy saved TokenResponse and SavedAuth.
Note that for Microsoft OAuth users should perform logaut manually in a web brosers.
SignOut(logout: true) will redirect users to the logout page. Without this, even with TokenResponse and SavedAuth destroyd, Microsoft OAuth will return saved user session. Please let me know if the issue is now solved,

**Comment by aayoub1** [comment]
When using SignOut(logout: true) the explorer blocks the popup and thus the the signout fails.
When enabling popups the signout finished successfully. Anyway to prevent the explorer from blocking the popup?

**Comment by hippogamesunity** [comment]
No, the asset can't control the default browser's behaviour and settings.

**Comment by aayoub1** [comment]
What is the reason that the initial sign-in opens a new tab without issue, but the sign-out does not open the tab and gets blocked?

**Comment by hippogamesunity** [comment]
Idk, from our side, the asset just calls 'Application.OpenURL' in both cases. We can not handle further behaviour.
