### ISSUE TITLE
Minor fix for compilation errors.

### ISSUE THREAD

**Issue by maxgmer** [hippogamesunity/SimpleSignIn#2]
Is it possible to include something like this into "GoogleAuthSettings"?
Just to avoid compilation errors (you can throw here instead of "null", also fine).

Can't build Addressables for DedicatedServer platform, as scripts don't compile because of this.
<img width="1117" alt="Screenshot 2024-06-10 at 18 15 27" src="https://github.com/hippogamesunity/SimpleSignIn/assets/24964174/b46ddc66-8596-4448-ae70-77f458688dcd">

**Comment by hippogamesunity** [comment]
Added in 4.2.
