### ISSUE TITLE
How do i open the google login web screen in landscape mode?

### ISSUE THREAD

**Issue by Dotanhedonia** [hippogamesunity/SimpleSignIn#20]
Hi, nice plugin

How do i open the google login web screen in landscape mode?

**Comment by hippogamesunity** [comment]
Hello, refer to your system settigns and default browsers setting.
Hold your device in landscape to open a default browsers in landscape mode.

**Comment by Dotanhedonia** [comment]
the game is in landscape, so i cannot force it to open in landscape?

**Comment by hippogamesunity** [comment]
The asset just makes a call 'Application.OpenURL', it can't control further behaviour, i.e. what browser will handle the link and how it will handle it.
