### ISSUE TITLE
Google sign in: after clicking on "Continue" gets stuck on loading screen

### ISSUE THREAD

**Issue by Dotanhedonia** [hippogamesunity/SimpleSignIn#21]
Google sign in: after clicking on "Continue" gets stuck on loading screen

![Screenshot_2024-08-11-18-26-31-02_40deb401b9ffe8e1df2f1cc5ba480b12 (1)](https://github.com/user-attachments/assets/bf9f7dc4-c1c0-4fa5-97e0-9cea1d9dd6bc)

**Comment by hippogamesunity** [comment]
Hello, you have incorrect deep linking setup, please read setup steps carefully and make sure that your app can handle deep links.

**Comment by Dotanhedonia** [comment]
ok it works thanks

**Comment by hippogamesunity** [comment]
Thanks for letting me know! May I ask you to leave a review on the Asset Store? Thanks and good luck!
