### ISSUE TITLE
Spellings in Wiki

### ISSUE THREAD

**Issue by StoneCypher** [hippogamesunity/SimpleSignIn#22]
Your wiki is locked to outsiders or I'd fix it myself

https://github.com/hippogamesunity/SimpleSignIn/wiki/Common-issues

Twice "guarantee" is spelled "guaranty"

**Comment by hippogamesunity** [comment]
Hello, thanks, I'll fix this!

пн, 26 авг. 2024 г., 17:55 John Haugeland ***@***.***>:
