### ISSUE TITLE
Packages deprecated in Unity Asset Store

### ISSUE THREAD

**Issue by divieirasilva** [hippogamesunity/SimpleSignIn#24]
Hello I recently purchased Google Simple Signin and Apple Simple Signin, but today I saw that both packages are now deprecated in Unity Asset Store. 

Can you explain to me why? Should I stop using them? 

Thank you,
Diego Vieira

**Comment by hippogamesunity** [comment]
Hello! Please check #news in our Discord channel. You can continue using my assets.
