### ISSUE TITLE
Facebook iOS18 Webview

### ISSUE THREAD

**Issue by CyLimitGame** [hippogamesunity/SimpleSignIn#25]
Hi,
The plugin works well for version under iOS18. 
On 18, when opening the webview for Facebook Login, the page stays blank and doesn't load.
Only tried for now on simulators, not on devices. But for iOS<18, it works for both.

ty

**Comment by CyLimitGame** [comment]
Tested on device iOS18, it works so it is just a webview problem from simulators.

**Comment by hippogamesunity** [comment]
Thanks for letting me know!
