### ISSUE TITLE
I can't access my account

### ISSUE THREAD

**Issue by AzhariMabar** [hippogamesunity/SimpleSignIn#26]
i can't access my account when logging in on Android. Here’s the photo.

![WhatsApp Image 2024-10-23 at 12 51 18](https://github.com/user-attachments/assets/f5941784-a93d-4224-bac1-571780edec6b)

When loading the account, Google reloads to the main page, and nothing happens in the app.

**Comment by hippogamesunity** [comment]
Hello, check your deep linking settings https://github.com/hippogamesunity/SimpleSignIn/wiki/Google

**Comment by bloneedu** [comment]
same problem

**Comment by hippogamesunity** [comment]
All you need is to perform steps from
https://github.com/hippogamesunity/SimpleSignIn/wiki/Google#preconditions
https://github.com/hippogamesunity/SimpleSignIn/wiki/Google#setup-steps

If you have any issues, please make a video that demonstrates all your environment and settings.
