### ISSUE TITLE
Authentication does not work in safari

### ISSUE THREAD

**Issue by leojungjung** [hippogamesunity/SimpleSignIn#5]
Hi. I had a problem with Google authentication in webgl, with Google and Opera they work perfectly, both on PC and on cell phones (Android and IOS), but when I try to log in to Safari nothing happens, nothing opens, not even a page from Google or the Authorization Middleware. I disabled the Block Pop-ups option in the safari configuration, now an alert appears saying if I want it to open a new tab, so I can log in with Google, but when I return from authorization Middleware it returns User Cancelled.

Video showing the error: [https://drive.google.com/file/d/1Q3-nK-WM20tmMLywD4Vh-x_z0A_3H35G/view?usp=sharing](url)

**Comment by hippogamesunity** [comment]
Hello! Just want to note, that my asset can't manage anything happens after
redirecting users to oauth endpoint with Application.OpenURL. Some browsers
may block new tabs, deep links or limit webgl content in any way. As the
first issue was solved and you can visit Google oauth endpoint, I would
recommend to check deep linking settings in Safari, maybe they are also
blocked for some reason.

чт, 4 июл. 2024 г., 15:44 Léo Jung Neves ***@***.***>:

**Comment by hippogamesunity** [comment]
Can you share the link to your app?

чт, 4 июл. 2024 г., 16:00 Léo Jung Neves ***@***.***>:

**Comment by hippogamesunity** [comment]
Also I was wrong about deep linking, for WebGL there is no deep linking,
Middleware should show you a message to return to the app. The app requests
an oauth with a web request when activated.

чт, 4 июл. 2024 г., 16:22 Hippo Games ***@***.***>:

**Comment by leojungjung** [comment]
yess, [https://feira-de-jogos.dev.br](url)

**Comment by leojungjung** [comment]
Did you find any solution?

**Comment by hippogamesunity** [comment]
> Safari is relatively more strict when compared to Chrome or Firefox, in terms of handling browser permissions. And then there’s limitations of Application.OpenURL API for WebGL
https://forum.zap.works/t/urgent-please-link-to-external-page-inside-webgl-doesnt-work-on-safari/8981/4

You can allow popups in Safari settings
![image](https://github.com/user-attachments/assets/6ac6369a-1a5a-41ab-83b5-14277c68c261)

Unfortunately, there is nothing I can do on my side. If your browsers blocks opening new tabs, the OAuth screen can't be opened.

Please let me know if I can help you with anything else.

**Comment by leojungjung** [comment]
ok, thanks for the help
