### ISSUE TITLE
Twitter login problem

### ISSUE THREAD

**Issue by sukk630** [hippogamesunity/SimpleSignIn#7]
Using Demo for Twitter is, to get the Token successfully, but failed to get the player information, and then the WEBGL side, there is an error when logging in, prompt: “Access to fetch at 'https://api.twitter.com/2/oauth2/token' from origin 'http://localhost:8085' has been blocked by CORS policy”

**Comment by hippogamesunity** [comment]
Thanks for reporting, I'll check it.

**Comment by hippogamesunity** [comment]
I had to add CORS proxy for WebGL (only for https://api.twitter.com/2/oauth2/token, https://api.twitter.com/2/oauth2/revoke and https://api.twitter.com/2/users/me). Just update the asset to v1.2. And don't forget to leave a review, bro!
