### ISSUE TITLE
Cannot resolve destination host: hippogames.dev

### ISSUE THREAD

**Issue by onurclb** [hippogamesunity/SimpleSignIn#8]
We have a problem with facebook sign-in. At first implementation everything was perfect. But today we trying to facebook sign-in encountered this message: "Cannot resolve destination host: hippogames.dev"

Our users can't logged in my game when migrated to simple sign-in. Please fix this issue rapidly.

We tested on Android and iOS

**Comment by hippogamesunity** [comment]
Hello! There are probably technical issues on my hosting provider. Hope it
will be resolved soon.

пт, 12 июл. 2024 г., 14:42 Onur ***@***.***>:

**Comment by onurclb** [comment]
We get 1 star review from users. We know you will do your best

Thanks

**Comment by hippogamesunity** [comment]
As mentioned in wiki, you can deploy your own middleware to control
everything on your side. Unfortunately, there is nothing I can do right
now, I just rent web-hosting.

пт, 12 июл. 2024 г., 15:02 Onur ***@***.***>:

**Comment by hippogamesunity** [comment]
Fixed.

пт, 12 июл. 2024 г., 15:28 Hippo Games ***@***.***>:
