### ISSUE TITLE
A question before purchasing, why not just use Googls Unity SDK?

### ISSUE THREAD

**Issue by drew-fc** [hippogamesunity/SimpleSignIn#9]
hi,

I am looking to implement google and apple login in a mobile app for ios and android.
I came across your tool which seems really nice quality.
I am just wondering, why would I just not use the Google Unity SDK here? https://github.com/googlesamples/google-signin-unity
I am trying to understand the differences, as that seems like a simple SDK to achieve google sign in, and avoids step of usingg a web browser, but I guess I am missing something.
Appreciate your help.

**Comment by hippogamesunity** [comment]
Hi! Yes, you can try this obsilete plugin (last update 6y). It's native, right, and not cross platform. So it's up to you. Personally, I was unable to make it working in my project)
